name: Lotto V8 Backtest Automatizzato2

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Ti permette di avviare il test manualmente con un clic

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    steps:
    - name: Cambia codice sorgente
      uses: actions/checkout@v4

    - name: Configura Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Esegui Test Storico V8
      run: |
        if [ -f genera_risultati.py ]; then
          python trova_coppia_perfetta.py
        else
          echo "Errore: Il file genera_risultati.py non esiste nella repository!"
          exit 1
        fi

